### ISSUE TITLE
教程缺失，如何添加workflow？

### ISSUE THREAD

**Issue by lukemin** [wangziyingwen/AutoApiSR#1]
第五步，点击右上角星星/star立马调用一次，再点击上面的Action就能看到每次的运行日志，看看运行状况

（必需点进去Test Api看下，api有没有调用到位，有没有出错。外面的Auto Api打勾只能说明运行是正常的，我们还需要确认10个api调用成功了，就像图里的一样。如果少了几个api，要么是注册应用的时候赋予api权限没弄好；要么是没登录激活onedrive，登录激活一下）
如何添加？
![1585118946(1)](https://user-images.githubusercontent.com/12003375/77509523-d88e0000-6ea7-11ea-8fa2-74b31e2dec90.png)

**Comment by wangziyingwen** [comment]
刷新啊，还没出来就点多几次star

**Comment by lukemin** [comment]
出现了，但是卡在testapi了。要等多长时间？

**Comment by wangziyingwen** [comment]
我都有写啊ORZ，AutoApiSR运行完要一到两小时

**Comment by lukemin** [comment]
看到了，谢谢帮助。
