### ISSUE TITLE
建议开发多账号

### ISSUE THREAD

**Issue by 1621391916** [wangziyingwen/AutoApiSR#2]
我有好几个号想续订，但不可能去创这么多github账号吧。
建议大佬开发多账号功能

**Comment by wangziyingwen** [comment]
其实不需要建很多github账号啊，建个分支就好了。或者把代码下载下来，新建项目再把代码上传上去。
多账号在测试，你要试试么
https://github.com/wangziyingwen/AutoApiS

**Comment by 1621391916** [comment]
嗯我试试
