### ISSUE TITLE
运行了两次都报同样都错了，怎么解决呢

### ISSUE THREAD

**Issue by likecreep** [wangziyingwen/AutoApiSR#4]
Run python 1.py
Traceback (most recent call last):
  File "1.py", line 86, in <module>
    main()
  File "1.py", line 40, in main
    access_token=gettoken(refresh_token)
  File "1.py", line 31, in gettoken
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'

**Comment by wangziyingwen** [comment]
refresh_token错了，注意id、机密格式位置是否正确。重新获取一遍token，严重注意token格式

**Comment by likecreep** [comment]
> refresh_token错了，注意id、机密格式位置是否正确。重新获取一遍token，严重注意token格式

修好了，谢谢
